// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tofoatpggdudjvgoixwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZm9hdHBnZ2R1ZGp2Z29peHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTE5NTEsImV4cCI6MjA2NDg2Nzk1MX0.szgJXH6rKE7DY4uB6SvITfNQXJeOjJUB5lZQGsiqIGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);